---
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: minimal

before_install:
  - URL=https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - curl -sLO "${URL}"
  - chmod +x uninstall
  - ./uninstall --force
  - rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew
  - sudo rm -rf /Library/Developer/CommandLineTools

install:
  - printf '[defaults]\nroles_path=./roles/\ninventory = inventory' > ansible.cfg

script:
  - make install_pip
  - hash pip 2>/dev/null || { echo >&2 "pip not installed. Aborting."; exit 1; }
  - which pip
  - pip --version

  - make install_ansible
  - hash ansible 2>/dev/null || { \
      echo >&2 "ansible not installed. Aborting."; exit 1; }
  - which ansible
  - ansible --version

  - make install_commandlinetools
  - xcode-select -p

  - hash brew 2>/dev/null || { echo >&2 "homebrew not installed.";
  - make install_homebrew
  - brew --version

  - make clean
