---
sudo: required
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: minimal

install:
  - printf '[defaults]\nroles_path=./roles/\ninventory = inventory' > ansible.cfg

script:
  - export PATH="$HOME/Library/Python/2.7/bin:$PATH"
  - make install_pip
  - pip --version

  - make install_ansible
  - ansible --version

  - make install_galaxy_roles
  - make install_commandlinetools
  - make install_python3

  - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  - export PATH="$HOME/Library/Python/3.7/bin:$PATH"
  - python --version
  - ansible --version
  - pip --version
